version: '3'
services:
  httpd:
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - ./website:/dashboard/apache2/htdocs
 restart: always
 /home/student/Web-Essentials-Project2/Website/dashboard
